name = "smartseniors"
compatibility_date = "2024-01-15"
pages_build_output_dir = "pages"

[[d1_databases]]
binding = "DB"
database_name = "smartseniors-db"
database_id = "3c1a84ef-2d23-42d4-853a-748f0cc16847"
